server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: https://nacos.tyu.wiki
#        server-addr: http://192.168.1.105:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            maxAge: 360000
            exposedHeaders: '*'
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lowerCaseServiceId: true
          filters:
            - StripPrefix=0
      routes:
#        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          #uri: http://localhost:8001          #匹配后提供服务的路由地址
#          uri: http://news.baidu.com/guoji #匹配后提供服务的路由地址
#          predicates:
#            - Path=/guoji/**         # 断言，路径相匹配的进行路由
        - id: ui
          uri: http://192.168.1.150:8010/
          predicates:
            - Path=/ui/**
        - id: typing-service
          uri: lb://typing-service
          predicates:
            - Path=/typing-service/account/**,/typing-service/version/**,/typing-service/wordLib/**
#          filters:
#            - RewritePath=/typing-service(?<segment>/?.*), /typing-service/typing-service$\{segment}
#            - StripPrefix=1

        - id: typing-service-ws
          uri: lb:ws://typing-service
          predicates:
            - Path=/typing-service/webSocket/**
  #          filters:
#            - StripPrefix=1

  redis:
    host: remotehost
    port: 9736

jwt:
  expirationTime: 86400000
  secretKey: haofangErpJwtSecretKey
  ignore:
    - /typing-service/account/login
    - /typing-service/account/register
    - /typing-service/version/**
    - /doc.html
    - /swagger-resources
    - /**/v3/api-docs
    - /webjars/**