server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: https://nacos.tyu.wiki
#        server-addr: http://192.168.1.105:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: http://news.baidu.com/guoji #匹配后提供服务的路由地址
          predicates:
            - Path=/guoji/**         # 断言，路径相匹配的进行路由

        - id: account
          uri: lb://typing-service
          predicates:
            - Path=/account/**

  redis:
    host: remotehost
    port: 9736

jwt:
  expirationTime: 86400000
  secretKey: haofangErpJwtSecretKey
  ignore:
    - /account/login
    - /account/register